### PR TITLE
Add PO update script for phpmyadmin repo

### PR DESCRIPTION
**Pull request by mauriciofauth**
I created a script to automatically update the PO files, instead of manually running the `./scripts/update-po` script every time.

I think automatically updating the `master` branch is enough, since usually there is not much changes in QA branches.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Nice!
At what schedule should we make it run?

**Comment by mauriciofauth** [comment]
> Nice!
> At what schedule should we make it run? 

Once or twice a week is good enough.

**Comment by williamdes** [comment]
> > Nice!
> > At what schedule should we make it run?
> 
> Once or twice a week is good enough.

I would say once a month ?
phpmyadmin/phpmyadmin#16529 is a good reason for this, users that use Git have a lot of diffs to checkout and new contributors too
Maybe that will avoid frequent big diffs in the repo

**Comment by mauriciofauth** [comment]
> I would say once a month ?

I think that will create bigger diffs than running more frequently. 

> [phpmyadmin/phpmyadmin#16529](https://github.com/phpmyadmin/phpmyadmin/issues/16529) is a good reason for this, users that use Git have a lot of diffs to checkout and new contributors too
> Maybe that will avoid frequent big diffs in the repo

There is not much we can do about that. phpMyAdmin is a really big repository with 120k+ commits. Any repository that big will be slow to clone.

**Comment by williamdes** [comment]
> > I would say once a month ?
> 
> I think that will create bigger diffs than running more frequently.
> 
> > [phpmyadmin/phpmyadmin#16529](https://github.com/phpmyadmin/phpmyadmin/issues/16529) is a good reason for this, users that use Git have a lot of diffs to checkout and new contributors too
> > Maybe that will avoid frequent big diffs in the repo
> 
> There is not much we can do about that. phpMyAdmin is a really big repository with 120k+ commits. Any repository that big will be slow to clone.

Yup, okay
Once a week is okay for me
Maybe Isaac would have some advice on what user should run this cron ?
Or maybe @mauriciofauth you could build a GitHub actions worflow for that using the cron feature ?

**Comment by mauriciofauth** [comment]
> what user should run this cron ?

`localized_docs` updates are done by the @phpmyadmin-bot.

**Comment by williamdes** [comment]
> > what user should run this cron ?
> 
> [localized_docs](https://github.com/phpmyadmin/localized_docs) updates are done by the @phpmyadmin-bot.

Yeah, I meant on the server :p 
Using actions would be a nice way to run the script

**Comment by mauriciofauth** [comment]
Closed in favor of https://github.com/phpmyadmin/phpmyadmin/pull/16955.

**Pull request closed without merging**
